# Generated by Django 2.0.5 on 2018-05-16 04:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EntradaMercanciaAPP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntradaMercancia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.IntegerField(default=1)),
                ('remision', models.CharField(max_length=30)),
                ('fecha', models.DateTimeField(verbose_name='Fecha de Ingreso')),
                ('comentarios', models.CharField(max_length=200)),
                ('costoTotal', models.FloatField()),
                ('cantidadTotal', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('alias', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='entradamercancia',
            name='idProveedorFk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EntradaMercanciaAPP.Proveedor'),
        ),
        migrations.AddField(
            model_name='entradamercancia',
            name='idUsuarioFk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
