# Generated by Django 2.0.5 on 2018-05-20 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EntradaMercanciaAPP', '0003_auto_20180516_1914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entradamercanciaproducto',
            old_name='cantidadTotal',
            new_name='cantidad',
        ),
        migrations.RenameField(
            model_name='entradamercanciaproducto',
            old_name='costoTotal',
            new_name='costo',
        ),
    ]
