# Generated by Django 2.0.5 on 2018-05-20 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EntradaMercanciaAPP', '0004_auto_20180520_1815'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Existencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('idBodegaFk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EntradaMercanciaAPP.Bodega')),
                ('idProductoFk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EntradaMercanciaAPP.Producto')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StatusCatalogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='status',
            name='idStatusCatalogoFk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EntradaMercanciaAPP.StatusCatalogo'),
        ),
        migrations.AddField(
            model_name='existencia',
            name='idStatusFk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EntradaMercanciaAPP.Status'),
        ),
    ]
