# Generated by Django 2.0.5 on 2018-05-20 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EntradaMercanciaAPP', '0005_auto_20180520_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradamercancia',
            name='idStatusFk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='EntradaMercanciaAPP.Status'),
        ),
        migrations.AddField(
            model_name='entradamercanciaproducto',
            name='idStatusFk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='EntradaMercanciaAPP.Status'),
        ),
    ]
